### ISSUE TITLE
Feature Request: Manual individual control of motors for troubleshooting

### ISSUE THREAD

**Issue by JDogHerman** [BarbourSmith/FluidNC#56]
A temporary override function and control over specific motors allow someone the ability to release a stuck belt.

**Comment by BarbourSmith** [comment]
Added!

**Comment by niccokunzmann** [comment]
Found it:

<img width="580" height="180" alt="Image" src="https://github.com/user-attachments/assets/754b313f-df7c-4ee0-ab38-f0fae63c24c2" />

Setup -> Extend all -> pull a belt.
