### ISSUE TITLE
Z menu has the word down misspelled.

### ISSUE THREAD

**Issue by JDogHerman** [BarbourSmith/FluidNC#57]
![image](https://github.com/BarbourSmith/FluidNC/assets/1299282/50eb6177-0676-43dd-a1b9-44109fdfff35)

![image](https://github.com/BarbourSmith/FluidNC/assets/1299282/7e58de01-b41e-4dc0-a67d-ad5eb9f3c53e)

From the index.html part of release (https://github.com/BarbourSmith/FluidNC/releases/tag/v0.63)...
![image](https://github.com/BarbourSmith/FluidNC/assets/1299282/93c74c41-688e-41d6-9bdd-e9300e9f755d)

**Comment by JDogHerman** [comment]
Maybe adding the verb jog or step then +up/-down might offer better clarity as well.

**Comment by JDogHerman** [comment]
the image on the user guide will also need to be updated. https://www.maslowcnc.com/user-guide

**Comment by JDogHerman** [comment]
This error appears to still exist in the index.html for the release of [v0.64](https://github.com/BarbourSmith/FluidNC/releases/tag/v0.64)

Line 42 Col 4568

![image](https://github.com/BarbourSmith/FluidNC/assets/1299282/4ceae129-1c31-4630-b762-ab623255e57d)

**Comment by BarbourSmith** [comment]
Fixed :)
