### ISSUE TITLE
Spelling error on FW Fluid v3.0.x "Cuurent"

### ISSUE THREAD

**Issue by JDogHerman** [BarbourSmith/FluidNC#58]
Current Pos is misspelled as Cuurent Pos: (double) U. rather than double R.

![image](https://github.com/BarbourSmith/FluidNC/assets/1299282/7973a4db-05e6-4f51-9fec-4229d7103fcc)

https://global.discourse-cdn.com/standard11/uploads/maslowcnc/original/3X/5/2/529aa390f9319446b6b9748205635d1158b83b6c.png

**Comment by BarbourSmith** [comment]
This should already be fixed in commit [c7171538621537224695394a40673bbd4efefa8b](https://github.com/BarbourSmith/FluidNC/commit/c7171538621537224695394a40673bbd4efefa8b)
