### ISSUE TITLE
Feature Request: active web connection checking

### ISSUE THREAD

**Issue by JDogHerman** [BarbourSmith/FluidNC#60]
The maslow.local webpage is responsive but it will send commands without regard if the maslow4 is still online. Maybe a heartbeat check could exist as some client side js code that lets the user know when the connection has been lost and to suspend possible future commands.

**Comment by BarbourSmith** [comment]
This is 100% an issue. I regularly click buttons expecting a response only to realize that the machine is off. This might be something that we want to do in conjunction with FluidNC since it's an issue that they share too.

**Comment by davidelang** [comment]
hasn't a heartbeat been implemented now?

**Comment by BarbourSmith** [comment]
It has!
